### ISSUE TITLE
Support non-exported properties 

### ISSUE THREAD

**Issue by DataPlusProgram** [4d49/object-inspector#17]
From what I can see this addon only supports viewing the exported properties of an object.

Would it be possible to add the option to view all an objects properties including the default ones?

**Comment by 4d49** [comment]
You can override the `is_valid_property` function. Or wait for me to implement this function, I had it in my plans.

**Comment by DataPlusProgram** [comment]
Okay I was able to achieve the desired affect by doing the following:

```
func _update_property_list() -> void:
	if is_instance_valid(_object):
		_valid_properties = _object.get_property_list()
	else:
		_valid_properties = []
	
	if !show_internal:
		var counter: int = 0
		
		var i: int = _valid_properties.size() - 1
		while i >= 0:
			var property: Dictionary = _valid_properties[i]
			if property["usage"] == PROPERTY_USAGE_SUBGROUP or property["usage"] == PROPERTY_USAGE_GROUP:
				if counter < 1:
					_valid_properties.remove_at(i)

				counter -= 1
			elif property["usage"] == PROPERTY_USAGE_CATEGORY:
				if counter < 1:
					_valid_properties.remove_at(i)

				counter = 0
			elif not is_valid_property(property):
				_valid_properties.remove_at(i)
			else:
				counter += 1

			i -= 1
	else :
		_valid_properties.reverse()

	update_inspector()
```

And then exporting the show_internal variable to toggle this behaviour on or off

```@export var show_internal : bool = false```

**Comment by 4d49** [comment]
@DataPlusProgram needs your testing.

**Comment by DataPlusProgram** [comment]
Currently my project is on 4.3 once 4.4 is released I will be able to test.
