### ISSUE TITLE
property_changed event

### ISSUE THREAD

**Issue by angedelamort** [4d49/object-inspector#3]
Hi,
I just added a new feature and wanted to do a new pull request but I don't have access. 
The feature is that when you change a value in the object inspector, it sends a signal.

**Comment by 4d49** [comment]
> Hi, I just added a new feature and wanted to do a new pull request but I don't have access. 

Hi! Maybe you tried to send the commit directly to master? Try fork the repository and send a pull resuest from the fork.

**Comment by angedelamort** [comment]
Thanks, I wasn't used to work with the fork workflow. Now it seems to work fine!

**Comment by 4d49** [comment]
@angedelamort should the signal only notify about the fact that the property has changed, or should it also send a new value?
